### ISSUE TITLE
BGS panel

### ISSUE THREAD

**Issue by sporebat** [aarronc/hutton-helper#29]
What tick are we in? Around how long until the next tick? What's our influence in this system? What's our influence margin in this system? What's our work advice for this system (needs #20)?

**Comment by sporebat** [comment]
![image](https://user-images.githubusercontent.com/23209850/45471815-94c81f80-b775-11e8-942d-55e60b85ea29.png)

First version will only display after `FSDJump`. @aarronc could you provide a server side JSON summary of the latest `Factions` for each of our systems? That way I can a) pull it and inform commanders of their situation at startup, and b) display the entire list for anyone thus inclined.

**Comment by sporebat** [comment]
No, wait. Forgot the tick.

**Comment by sporebat** [comment]
^ I can put that in the header for the full table perhaps

Is on by default OK for this one, or should it be off by default?

**Comment by sporebat** [comment]
Just realised I'm depending on the server to tell me the tick number, too. Aah, well.

**Comment by sporebat** [comment]
@aarronc, mind some tweaks to that route? In no particular order:

* We can infer the list of Hutton systems from the rest of the data
* I'd prefer to store numbers as numbers
* I'd much appreciate the margin for the current tick
* Arrays are a little more flexible than properties named after time spans
* If we know the tick end, we know the tick start, and vice versa

If we want it to be future-proof and don't mind it being _huge_, we could just have a `Ticks` array each with `TickNumber`, `TickEnd`, and a `Systems` array of the `StarSystem`, `SystemFaction`, and abbreviated `Factions` entries from the `FSDJump` events.


```json
{
    "Ticks": {
        "TickNumber": 1040,
        "TickEnd": "2018-09-17T16:59:59Z",
        "Systems": [
            {
                "StarSystem": "Ross 671",
                "Factions": [
                    {
                        "Name": "Social Ross 671 for Equality",
                        "FactionState": "Boom",
                        "Influence": 0.176647
                    },
                    {
                        "Name": "Hutton Orbital Truckers Co-Operative",
                        "FactionState": "None",
                        "Influence": 0.323353
                    }
                ],
                "SystemFaction": "Social Ross 671 for Equality"
            }
        ]
    }
}
```

The front-end could then cope with gaps in the current and previous ticks, compute margin, or even display graphs if we got really ambitious. I'd think I'd rather leave it in the web UI, just calling it out as possible. Heh.

A smaller representation just for what we'd need now might be:

```json
{
    "Ticks": [
        {
            "State": "None",
            "Systems": {
                "PSPF-LF 2": {
                    "Influence": 0.529703,
                    "Margin": 0.367299
                }
            },
            "TickNumber": 1040,
            "TickEnd": "2018-09-17T16:59:59Z"
        },
        {
            "State": "Election",
            "Systems": {
                "PSPF-LF 2": {
                    "Influence": 0.516353,
                    "Margin": 0.3172
                }
            },
            "TickNumber": 1039,
            "TickEnd": "2018-09-16T16:59:59Z"
        }
    ]
}
```
You could put `Advice` either in the latest tick or at the top next to `Ticks`. I think I'd probably prefer the latter, but I trust you'll come up with something good.

**Comment by aarronc** [comment]
Big we can do! Have a look at the general.json again, I've updated it to reflect the first JSON example

**Comment by sporebat** [comment]
Awesome! May as well drop the top level `Ticks` if there's just one of it, though.
