### ISSUE TITLE
News to expand and wrap with window size.

### ISSUE THREAD

**Issue by aarronc** [aarronc/hutton-helper#30]
it currently wraps in a strange way. Get it to wrap with Window Width

**Comment by sporebat** [comment]
[Landing Pad](https://github.com/bgol/LandingPad) can figure out how wide to make itself. Might help.

**Comment by sporebat** [comment]
Maybe a `ttk.Text` instead?

**Comment by sporebat** [comment]
Maybe not.

![image](https://user-images.githubusercontent.com/23209850/45469053-3433e500-b76b-11e8-9a4d-e9c14e2cb8ff.png)

**Comment by sporebat** [comment]
This'll follow the window. It's not going to hyphenate automatically, so you'll occasionally get a ragged gap caused by a big word, but it'll do.

![image](https://user-images.githubusercontent.com/23209850/45469512-297a4f80-b76d-11e8-9faf-61b718ce4d49.png)

**Comment by sporebat** [comment]
Hang on... I'm going to need to do this to the status, too, eh?

Reckon we should make the News: label the link, and display the news more plainly? Then I could extract a `WrappingLabel` widget and do both with one class.

**Comment by sporebat** [comment]
This closable now?
