### ISSUE TITLE
Send helper uptime to server

### ISSUE THREAD

**Issue by sporebat** [aarronc/hutton-helper#31]
Also send a unique ID calculated at launch time. Smuggling them into posted events should be fine.

**Comment by aarronc** [comment]
I've thought about this for a while, smuggling them into events is a nice way to get them in BUT it will not give you an accurate way to calculate uptime for people who have the Hutton Helper open but are away from the PC or sat in a station while in cubicle 3. The Hutton Helper does not POST data until the player does something that is on the XMIT list. 

I think a better way is to attach a UUID to the news request, as this would pull data from the HH backend server on a regular basis. this can be generated on the load of news.py. 

I've committed a working version and adjusted the backend server to see the UUID 👍
