### ISSUE TITLE
the 'Its Getting Warm in here' event causes the Helper to crash

### ISSUE THREAD

**Issue by aarronc** [aarronc/hutton-helper#34]
When your heat goes over 100% the helper displays, It's getting warm in here and the news rapidly changes size by 1-2 pixels and then the Helper fails to respond.

**Comment by sporebat** [comment]
I can't reproduce this if it needs 4K, but here's what I'd try if I could:

* In `HuttonNews.__configure_event`, print `event.width`
* Heat yourself up
* Watch the fun

If you get a lot of spam with kinda consistent width, try setting `width = max([self.width, event.width])` and call `self.configure` only if `width != self.width`. If it keeps racing away, maybe keep track of the count and give up after 20?

**Comment by sporebat** [comment]
Oh, and start with `self.width = float('-inf')`.

**Comment by sporebat** [comment]
Oh, this is going to keep happening until we wrap the status. See #30.
