### ISSUE TITLE
Shopping not always detecting purchase

### ISSUE THREAD

**Issue by sporebat** [aarronc/hutton-helper#41]
As [reported by @aarronc]:(https://github.com/aarronc/hutton-helper/commit/f5c42a38646669e04a5bc8a1b97d8e5ded2d2956#commitcomment-30542022)
> buying the ore does not update the 'in hold' amount

Caused by `MarketBuy` missing `Type_Localised`

**Comment by aarronc** [comment]
do you want me to find or compile a list of Localised and $xxx_name combinations so we can have a dict or something we can reference?

**Comment by sporebat** [comment]
If the new mechanism turns out to be reliable, we won’t need it.

Maybe just in case. The list scraped from missions wasn’t compete, but if you go through all the events you should do pretty well.

**Comment by sporebat** [comment]
Is this looking fixed after #42?

**Comment by sporebat** [comment]
Closing until someone mentions it again.
