### ISSUE TITLE
Logistics is your friend Commander

### ISSUE THREAD

**Issue by aarronc** [aarronc/hutton-helper#44]
I love the Shopping list feature, having a list that checks off is amazing, showing some love for people taking delivery missions and passengers is also something I think would really enhance the helper. 

when you take a data, passenger, planetary scan mission or anything that is going from A -> B, this would let people to calculate routes. Make the system name clickable to copy into the clipboard so its a simple copy and paste into the galaxy map, I don't think stacking is necessary. Just a straight list that deletes on mission complete. see the mock-up image
![prop](https://user-images.githubusercontent.com/1708701/45710447-954e2500-bb7e-11e8-8051-be7737e607c3.jpg)

**Comment by NoFoolLikeOne** [comment]
That looks very cool, Are you able to turn these features on and off in settings?

**Comment by sporebat** [comment]
You can turn off the shopping list table ("Missions need:") and sections of the progress table ("Progress:"). If you turn off all the sections of the progress table, or if there's no progress, it disappears. If there are no commodities to get for a mission, that table disappears, too. Finally: that UNSOLD line only appears if it's enabled AND the value is not zero.

The delivery schedule, I think Aaron just mocked up. Rendered, I'd probably have it look similar to the others, though I like the use of the gray and the more tables we add the more we need the top left cell on each to be bold text.

**Comment by sporebat** [comment]
@aarronc destination in the list if there's a mission for delivery; remaining and cargo (empty for data); strike through if you don't have anything on board to remind you to pick some up? I've been there. Worse, I went shopping for it.

Saying it like that, strikes me we could combine it with the existing shopping list by adding a column: `to {}` if you have cargo, `from {}` if not and it's a delivery mission, (later) `FIND` if not and we can link to EDDB for finding it.

That'd be a little wider, but not much so, and avoid becoming twice as long under some circumstances.

Reasons to be careful: `CargoDepot` when picking up for a delivery mission gives you special cargo. You might well have some of the cargo already, but it can't be used for the delivery mission.  I'm not sure if you can eject the special cargo. If you can, I don't know how to tell which one you ejected. If you've got more than one mission for the same commodity, you need those different lines we just did all that work to eliminate. But, at least after you've picked up the cargo you'd get your destinations list. Hmm.

**Comment by sporebat** [comment]
Got the cargo tracking done. @aarronc could you check to see if there are any `Mission_PassengerVIP` with `Commodity` but without `DestinationSystem` or `DestinationStation`? I'm expecting some without `DestinationStation` unless they shove the tourist beacon name in there.

**Comment by sporebat** [comment]
I reckon this'll be the next thing we get the beta testers to beta test once the release is out there.

Also, FDev is trolling me with this `DestinationSystem`:

```json
{
    "timestamp": "2018-05-08T10:23:16Z",
    "event": "MissionAccepted",
    "Faction": "Fullerene C60 Raiders",
    "Name": "Mission_Sightseeing",
    "LocalisedName": "Ariadna Lynch seeks sightseeing adventure",
    "Commodity": "$Clothing_Name;",
    "Commodity_Localised": "Clothing",
    "Count": 1,
    "DestinationSystem": "Huveang De$MISSIONUTIL_MULTIPLE_FINAL_SEPARATOR;Meenates",
    "Expiry": "2018-05-09T00:39:05Z",
    "Wing": false,
    "Influence": "Med",
    "Reputation": "Med",
    "Reward": 853600,
    "PassengerCount": 2,
    "PassengerVIPs": true,
    "PassengerWanted": false,
    "PassengerType": "Tourist",
    "MissionID": 376810035
}
```

**Comment by sporebat** [comment]
Oh, it's a redirect! Hey @aarronc could you go spelunking for that in the database? Might be handy to be able to see those coming.

Longest `DestinationSystem` so far in my journal: 

* `Col 285 Sector YF-M c8-8`

Longest `DestinationStation` so far in my journal:

* `Levi-Strauss Installation`
* `Lopez de Villalobos Plant`
* `Rescue Ship - Gaiman Dock`

Even if I'm displaying only the station or the system name, I'm going to need to stretch the window wider to make it _and_ the commodity _and_ the counts show on a line.

**Comment by aarronc** [comment]
`{
   "hhstationname":null,
   "hhsystemname":"Sothis",
   "Name":"Mission_Sightseeing_name",
   "MissionID":422067687,
   "timestamp":"2018-09-26T23:00:03Z",
   "OldDestinationStation":"",
   "NewDestinationSystem":"Robigo",
   "commandername":"Clopster",
   "huttonappversion":"1.8.2",
   "event":"MissionRedirected",
   "OldDestinationSystem":"Sothis",
   "NewDestinationStation":"Hauser's Reach"
}`

something like this?

**Comment by sporebat** [comment]
Deliberately holding back on a PR for that until we've got a beta channel set up, but I'm pretty happy. Feel free to allude on the show to us having more in the lab just waiting for some extra testing.

**Comment by sporebat** [comment]
Ready for a little beta testing once #61.

**Comment by sporebat** [comment]
Hmm. Still TODO: data.

**Comment by sporebat** [comment]
Bug in the handling of data delivery missions: the `Cargo` event at game restart wipes the virtual cargo.

**Comment by sporebat** [comment]
It's not just at game start: re-logging will do it.
```
KeyError: 'data/422551673'
````
... and then they get stuck there forever.

**Comment by sporebat** [comment]
This is one of those features where the closer you get to complete, the more irritating it is that the rest hasn't been done. I found myself looking at the display for assassination missions, for example. Why isn't it telling me where to fly and honk next ARGH!?

Fortunately, it strikes me a lot of the mission types are solvable just keeping track of the destination. If that helps us be complete instead of irritatingly close to complete, awesome.
