### ISSUE TITLE
Opening Market.json on the Journal 'Market' event and passing that info to the Backround Server

### ISSUE THREAD

**Issue by aarronc** [aarronc/hutton-helper#48]
I have made a route for this /market/ and I may be missing something simple here but I can't get it to pass the market.json file contents over to the HH background server.

**Comment by sporebat** [comment]
I have code to reliably find it. Didn’t occur to me to use the `Market` event. Funny.

**Comment by aarronc** [comment]
it will always be market.json in the same directory as the journal files. is there a default path it uses when opening the Journal file?

**Comment by aarronc** [comment]
works perfectly!
