### ISSUE TITLE
The news is stale

### ISSUE THREAD

**Issue by sporebat** [aarronc/hutton-helper#64]
`#hutton-truckers-bgs-briefing`:
> Work for HOT in: wolf 359, Wise 0855-0714

`'/news.json/`:
> No Work to be done for MG in Wise, They have enough Gap now. Focus on the Lower % Hot systems

Server side, @aarronc, could you provide the timestamp of when the news was updated, then re-assign the issue to me? I'll then put a subtle indicator if it's getting out of date.

**Comment by aarronc** [comment]
added timestamp to news.json :)

**Comment by sporebat** [comment]
Thanks. The client end will have to wait a while, I'm afraid. This lurgy is a nasty one. Very few movement points, and a lot of other chasing around to do.
