### ISSUE TITLE
Opera security warning on the stats page

### ISSUE THREAD

**Issue by CMDR-Cometborne** [aarronc/hutton-helper#71]
When looking at https://hot.forthemug.com/stats.php in Opera, a warning is displayed that some content is insecure.  Looking at the page source shows the problem is  the inclusion of the javascript and css files from cloudflare in lines 121, 123, and 125 of the page.

**Comment by aarronc** [comment]
thanks for letting me know, i didnt have those javascipt entries prefixed with https
