### ISSUE TITLE
Options to hide UI

### ISSUE THREAD

**Issue by NoFoolLikeOne** [aarronc/hutton-helper#74]
I'd like to hide some of the UI such as the buttons and news to reduce the amount of screen that is used up. 

But I haven't quite figured out how this would work in the context of the plugin architecture.

**Comment by alterNERDtive** [comment]
Yes, please. Especially since something keeps resizing my EDMC window and I’m kind of suspecting the hutton helper right now. So close to forking and just removing the UI entirely :)

If I were better at Python I’d just do a pull request with an option to hide the UI, but I’m not.

**Comment by NoFoolLikeOne** [comment]
I'll confess that I edited my load.py

I added this just before the return value in plugin_app. 

frame.after(5000,this.frame.grid_remove)

It makes the frame disappear after 5 seconds. 

But its not ideal because really you want to have an option to hid each of the elements and you also want the frame to stay visible if there is an upgrade required.

**Comment by PsymonsB** [comment]
a lot of this issue is covered by the new lite version, news is something we want to keep as we can send messages to individual commanders who do not interact with social media etc. the issue of resizing is a separate issue that I've been unable to recreate or solve.
