### ISSUE TITLE
SAASignalsFound handling broken

### ISSUE THREAD

**Issue by CMDR-Cometborne** [aarronc/hutton-helper#76]
While debugging an EDMC crash, I came across quite a few error messages in the EDMC log file with the following content:

event: SAASignalsFound

404 POST http://forthemug.com:4567/saasignalsfound ms=142

'<!DOCTYPE html>\n<html>\n<head>\n  <style type="text/css">\n  body { text-align:center;font-family:helvetica,arial;font-size:22px;\n    color:#888;margin:20px}\n  #c {margin:0 auto;width:500px;text-align:left}\n  </style>\n</head>\n<body>\n  <h2>Sinatra doesn\xe2\x80\x99t know this ditty.</h2>\n  <img src=\'http://forthemug.com:4567/__sinatra__/404.png\'>\n  <div id="c">\n    Try this:\n    <pre># in app.rb\nclass MyApp\n  post &#x27;&#x2F;saasignalsfound&#x27; do\n    &quot;Hello World&quot;\n  end\nend\n</pre>\n  </div>\n</body>\n</html>\n'

**Comment by aarronc** [comment]
Thanks for letting me know. I had a typo in the back end route. All fixed now
