### ISSUE TITLE
Feature request: Less chatty

### ISSUE THREAD

**Issue by CMDR-Cometborne** [aarronc/hutton-helper#77]
After a typical play session, the EDMC log file isover 1 MB large, and most of that are debug/progress messages from the HH.  Whil such messages might be helpful if you are developing or debugging, they make it quite hard to find messages from EDMC or other plugins.

Can you please add a configuration option to make the HH less chatty and log only real problems?

**Comment by PsymonsB** [comment]
Will look at this tonight, your right will make only error codes be reported to the log. so no 200 or 204's

**Comment by PsymonsB** [comment]
will be in the next hh 2.2.09 update soon, or you can download from master
