### ISSUE TITLE
You'd better stock up on land mines

### ISSUE THREAD

**Issue by sporebat** [aarronc/hutton-helper#8]
[mentioned on Reddit](https://reddit.com/r/EliteDangerous/comments/9e4tzl/psa_vip_passenger_commodity_demands_are_generated/)
> by looking at the journal file, I can know EXACTLY what the VIP wants before they request it! Just check the "MissionAccepted" entry and plan accordingly. When your VIP General requests landmines for "comfort", you will be prepared to quickly, and efficiently, supply that need.

`MissionAccepted`, you say? I can look for that, display the commodity needed, and pop up your browser with the right EDDB query to find it when you click. No worries.

**Comment by sporebat** [comment]
Mechanism could also be used for source and return missions.

**Comment by sporebat** [comment]
@aarronc could you dig up some example events for `MissionAccepted` with VIP passenger demands, or for source and return missions?

**Comment by sporebat** [comment]
Relevant parts of the VIP mission event:
```json
{
    "Commodity_Localised": "Consumer Technology",
    "Commodity": "$ConsumerTechnology_Name;",
    "Count": 2,
    "DestinationSystem": "LTT 9360",
    "event": "MissionAccepted",
    "Expiry": "2018-09-08T18:26:17Z",
    "LocalisedName": "Transport Milo Cote",
    "MissionID": 417255854,
    "Name": "Mission_PassengerVIP",
    "timestamp": "2018-09-08T16:19:56Z"
}
```

**Comment by sporebat** [comment]
`MissionAccepted` events with this `Name` also have a `Commodity` and `Commodity_Localised`, but don't need an EDDB link:

* `Mission_Delivery`
* `Mission_Delivery_Boom`
* `Mission_Delivery_CivilUnrest`
* `Mission_Delivery_Cooperative`
* `Mission_Delivery_Democracy`
* `Mission_Delivery_Outbreak`

**Comment by sporebat** [comment]
Aah, here are the others that need us to go shopping:

* `Mission_Collect_Bust`
* `Mission_Collect_Industrial`
* `Mission_Collect_Outbreak`

(Yes, yes, wildcards.)

```json
{
    "Commodity_Localised": "Basic Medicines",
    "Commodity": "$BasicMedicines_Name;",
    "Count": 28,
    "DestinationStation": "Davies Station",
    "DestinationSystem": "Epsilon Eridani",
    "event": "MissionAccepted",
    "Expiry": "2018-09-09T17:38:05Z",
    "Faction": "Hutton Orbital Truckers Co-Operative",
    "LocalisedName": "Outbreak aid needed 28 units of Basic Medicines",
    "MissionID": 417282049,
    "Name": "Mission_Collect_Outbreak",
    "timestamp": "2018-09-08T17:48:51Z"
}
```

**Comment by aarronc** [comment]
Here is a full list of Delivery Missions 

- Mission_Delivery
- Mission_DeliveryWing
- Mission_DeliveryWing_Agriculture
- Mission_DeliveryWing_Boom
- Mission_DeliveryWing_CivilUnrest
- Mission_DeliveryWing_CivilWar
- Mission_DeliveryWing_Confederacy
- Mission_DeliveryWing_Cooperative
- Mission_DeliveryWing_Democracy
- Mission_DeliveryWing_Famine
- Mission_DeliveryWing_Outbreak
- Mission_DeliveryWing_War
- Mission_Delivery_Agriculture
- Mission_Delivery_Boom
- Mission_Delivery_CivilUnrest
- Mission_Delivery_CivilWar
- Mission_Delivery_Confederacy
- Mission_Delivery_Cooperative
- Mission_Delivery_Democracy
- Mission_Delivery_Famine
- Mission_Delivery_Founder
- Mission_Delivery_Outbreak
- Mission_Delivery_RankEmp
- Mission_Delivery_RankFed
- Mission_Delivery_War

**Comment by aarronc** [comment]
Just for Completeness :) here is the full list (maybe missing the new wing mission types) 

- Chain_ClearingThePath
- Chain_FindThePirateLord
- Chain_HelpFinishTheOrder
- Chain_MiningToOrder
- Chain_PlanetaryIncursions
- Chain_RegainFooting
- Chain_RescueFromTheTwins
- Chain_RescueTheWares
- Chain_SalvageJustice
- Chain_SalvageJustice_PersonalEffects
- Chain_SeekingAsylum
- Chain_WrongTarget
- Mission_Altruism
- Mission_AltruismCredits
- Mission_AltruismCredits_Bust
- Mission_AltruismCredits_CivilUnrest
- Mission_AltruismCredits_Famine
- Mission_AltruismCredits_Outbreak
- Mission_Altruism_Bust
- Mission_Altruism_CivilUnrest
- Mission_Altruism_Famine
- Mission_Altruism_Outbreak
- Mission_Altruism_Theocracy
- Mission_Assassinate
- Mission_AssassinateWing
- Mission_AssassinateWing_Legal_Bust
- MISSION_assassinateWing_legal_CivilUnrest
- Mission_AssassinateWing_Legal_CivilWar
- Mission_AssassinateWing_Legal_Communism
- Mission_AssassinateWing_Legal_Corporate
- Mission_AssassinateWing_Legal_Feudal
- Mission_AssassinateWing_Legal_Penal
- Mission_AssassinateWing_Legal_War
- Mission_Assassinate_Illegal_BLOPS
- Mission_Assassinate_Illegal_BLOPS_Bust
- Mission_Assassinate_Illegal_BLOPS_CivilUnrest
- Mission_Assassinate_Illegal_BLOPS_Election
- Mission_Assassinate_Illegal_BLOPS_Industrial
- Mission_Assassinate_Illegal_BLOPS_Outbreak
- Mission_Assassinate_Illegal_Founder_HighTech
- Mission_Assassinate_Illegal_Lockdown
- Mission_Assassinate_Illegal_Outbreak
- MISSION_assassinate_Illegal_Planetary
- Mission_Assassinate_Legal_Bust
- MISSION_assassinate_legal_CivilUnrest
- Mission_Assassinate_Legal_CivilWar
- Mission_Assassinate_Legal_Communism
- Mission_Assassinate_Legal_Corporate
- Mission_Assassinate_Legal_Feudal
- Mission_Assassinate_Legal_Penal
- Mission_Assassinate_Legal_War
- Mission_Assassinate_Planetary
- Mission_Assassinate_Planetary_Expansion
- Mission_Assassinate_RankEmp
- Mission_Assassinate_RankFed
- Mission_Collect
- Mission_CollectWing
- Mission_CollectWing_Bust
- Mission_CollectWing_CivilUnrest
- Mission_CollectWing_CivilWar
- Mission_CollectWing_Famine
- Mission_CollectWing_Industrial
- Mission_CollectWing_Outbreak
- Mission_Collect_Bust
- Mission_Collect_CivilUnrest
- Mission_Collect_CivilWar
- Mission_Collect_Famine
- Mission_Collect_Industrial
- Mission_Collect_Outbreak
- MISSION_Collect_RankEmp
- MISSION_Collect_RankFed
- Mission_Courier
- Mission_Courier_Boom
- Mission_Courier_CivilUnrest
- Mission_Courier_CivilWar
- Mission_Courier_Democracy
- Mission_Courier_Elections
- Mission_Courier_Engineer
- Mission_Courier_Expansion
- Mission_Courier_Famine
- Mission_Courier_Lockdown
- Mission_Courier_Outbreak
- Mission_Courier_RankEmp
- Mission_Courier_RankFed
- Mission_Courier_Service
- Mission_Courier_War
- Mission_Delivery
- Mission_DeliveryWing
- Mission_DeliveryWing_Agriculture
- Mission_DeliveryWing_Boom
- Mission_DeliveryWing_CivilUnrest
- Mission_DeliveryWing_CivilWar
- Mission_DeliveryWing_Confederacy
- Mission_DeliveryWing_Cooperative
- Mission_DeliveryWing_Democracy
- Mission_DeliveryWing_Famine
- Mission_DeliveryWing_Outbreak
- Mission_DeliveryWing_War
- Mission_Delivery_Agriculture
- Mission_Delivery_Boom
- Mission_Delivery_CivilUnrest
- Mission_Delivery_CivilWar
- Mission_Delivery_Confederacy
- Mission_Delivery_Cooperative
- Mission_Delivery_Democracy
- Mission_Delivery_Famine
- Mission_Delivery_Founder
- Mission_Delivery_Outbreak
- Mission_Delivery_RankEmp
- Mission_Delivery_RankFed
- Mission_Delivery_War
- MISSION_Disable
- Mission_Disable_BLOPS_Lockdown
- Mission_Disable_CivilUnrest
- Mission_Disable_CivilWar
- Mission_Disable_Expansion
- Mission_Disable_HighTech
- Mission_Disable_War
- Mission_DS_Collect
- Mission_DS_PassengerBulk
- MISSION_genericPermit1
- MISSION_Hack
- MISSION_Hack_BLOPS
- Mission_Hack_BLOPS_CivilWar
- Mission_Hack_BLOPS_Lockdown
- Mission_Hack_CivilWar
- Mission_LongDistanceExpedition
- Mission_LongDistanceExpedition_Explorer_Boom
- Mission_LongDistanceExpedition_Explorer_Expansion
- Mission_Massacre
- Mission_MassacreThargoid
- Mission_MassacreWing
- Mission_MassacreWing_Legal_Bust
- Mission_MassacreWing_Legal_CivilUnrest
- Mission_MassacreWing_Legal_Military
- Mission_Massacre_Conflict_CivilWar
- Mission_Massacre_Conflict_War
- Mission_Massacre_Illegal_BLOPS
- Mission_Massacre_Illegal_BLOPS_Bust
- Mission_Massacre_Illegal_BLOPS_CivilUnrest
- Mission_Massacre_Illegal_BLOPS_Elections
- Mission_Massacre_Illegal_BLOPS_Famine
- Mission_Massacre_Illegal_BLOPS_Outbreak
- Mission_Massacre_Legal_Bust
- Mission_Massacre_Legal_CivilUnrest
- Mission_Massacre_Legal_Military
- Mission_Massacre_Legal_PrisonColony
- Mission_Massacre_RankEmp
- Mission_Massacre_RankFed
- Mission_Massacre_Skimmer_CivilUnrest
- Mission_Massacre_Skimmer_Communism
- Mission_Massacre_Skimmer_Corporation
- Mission_Massacre_Skimmer_Expansion
- Mission_Massacre_Skimmer_Refinery
- Mission_Mining
- Mission_Mining_Boom
- Mission_Mining_Expansion
- Mission_Mining_Extraction
- Mission_PassengerBulk
- Mission_PassengerBulk_AIDWORKER_ARRIVING
- Mission_PassengerBulk_AIDWORKER_LEAVING
- Mission_PassengerBulk_BUSINESS_ARRIVING
- Mission_PassengerBulk_BUSINESS_LEAVING
- Mission_PassengerBulk_MEDICAL_ARRIVING
- Mission_PassengerBulk_POLITICIAN_ARRIVING
- Mission_PassengerBulk_POLPRISONER_ARRIVING
- Mission_PassengerBulk_PRISONEROFWAR_LEAVING
- Mission_PassengerBulk_PROTESTOR_ARRIVING
- Mission_PassengerBulk_REBEL_ARRIVING
- Mission_PassengerBulk_REBEL_LEAVING
- Mission_PassengerBulk_REFUGEE_LEAVING
- Mission_PassengerBulk_SCIENTIST_ARRIVING
- Mission_PassengerBulk_SECURITY_ARRIVING
- Mission_PassengerVIP
- Mission_PassengerVIP_Celebrity_BOOM
- Mission_PassengerVIP_CEO_BOOM
- Mission_PassengerVIP_CEO_BUST
- Mission_PassengerVIP_CEO_EXPANSION
- Mission_PassengerVIP_Criminal_BOOM
- Mission_PassengerVIP_Criminal_CIVILUNREST
- Mission_PassengerVIP_Doctor_CIVILWAR
- Mission_PassengerVIP_Doctor_FAMINE
- Mission_PassengerVIP_Doctor_OUTBREAK
- Mission_PassengerVIP_Doctor_WAR
- Mission_PassengerVIP_Explorer_EXPANSION
- Mission_PassengerVIP_General_WAR
- Mission_PassengerVIP_HeadofState_BUST
- Mission_PassengerVIP_HeadofState_CIVILUNREST
- Mission_PassengerVIP_HeadofState_CIVILWAR
- Mission_PassengerVIP_HeadofState_ELECTION
- Mission_PassengerVIP_HeadofState_FAMINE
- Mission_PassengerVIP_HeadofState_OUTBREAK
- Mission_PassengerVIP_HeadofState_WAR
- Mission_PassengerVIP_Scientist_CIVILWAR
- Mission_PassengerVIP_Scientist_FAMINE
- Mission_PassengerVIP_Scientist_OUTBREAK
- Mission_PassengerVIP_Scientist_WAR
- Mission_PassengerVIP_Terrorist_CIVILUNREST
- Mission_PassengerVIP_Terrorist_CIVILWAR
- Mission_PassengerVIP_Terrorist_OUTBREAK
- Mission_PassengerVIP_Terrorist_WAR
- Mission_PassengerVIP_Tourist_BOOM
- Mission_PassengerVIP_Tourist_ELECTION
- Mission_PassengerVIP_Tourist_EXPANSION
- Mission_Piracy_Anarchy
- Mission_Piracy_BLOPS
- Mission_Piracy_Boom
- Mission_Piracy_War
- Mission_Rescue
- Mission_Rescue_Agricultural
- Mission_Rescue_CivilUnrest
- Mission_Rescue_Cooperative
- Mission_Rescue_Elections
- Mission_Rescue_Outbreak
- Mission_Rescue_Planet
- Mission_RS_Massacre
- Mission_RS_PassengerBulk
- Mission_Salvage
- MISSION_Salvage_CivilUnrest
- MISSION_Salvage_CivilWar
- MISSION_Salvage_Expansion
- MISSION_Salvage_Famine
- MISSION_Salvage_Illegal
- MISSION_Salvage_Illegal_Bust
- MISSION_Salvage_Illegal_Expansion
- MISSION_Salvage_Illegal_Feudal
- MISSION_Salvage_Illegal_Terraforming
- MISSION_Salvage_Outbreak
- Mission_Salvage_Planet
- Mission_Salvage_RankEmp
- Mission_Salvage_RankFed
- MISSION_Salvage_Refinery
- MISSION_Salvage_War
- MISSION_Scan
- Mission_Scan_CivilUnrest
- Mission_Scan_CivilWar
- Mission_Scan_Lockdown
- Mission_Scan_War
- Mission_Sightseeing
- Mission_Sightseeing_CEO_BOOM
- Mission_Sightseeing_CEO_EXPANSION
- Mission_Sightseeing_Criminal_BOOM
- Mission_Sightseeing_Criminal_BUST
- Mission_Sightseeing_Criminal_CIVILUNREST
- Mission_Sightseeing_Criminal_CIVILWAR
- Mission_Sightseeing_Criminal_FAMINE
- Mission_Sightseeing_Criminal_OUTBREAK
- Mission_Sightseeing_Doctor_BUST
- Mission_Sightseeing_Doctor_CIVILUNREST
- Mission_Sightseeing_Doctor_CIVILWAR
- Mission_Sightseeing_Doctor_FAMINE
- Mission_Sightseeing_Doctor_OUTBREAK
- Mission_Sightseeing_Doctor_WAR
- Mission_Sightseeing_Explorer_EXPANSION
- Mission_Sightseeing_General_CIVILWAR
- Mission_Sightseeing_General_WAR
- Mission_Sightseeing_Scientist_CIVILWAR
- Mission_Sightseeing_Scientist_FAMINE
- Mission_Sightseeing_Scientist_OUTBREAK
- Mission_Sightseeing_Scientist_WAR
- Mission_Sightseeing_Terrorist_CIVILUNREST
- Mission_Sightseeing_Terrorist_CIVILWAR
- Mission_Sightseeing_Terrorist_OUTBREAK
- Mission_Sightseeing_Terrorist_WAR
- Mission_Sightseeing_Tourist_BOOM
- Mission_Sightseeing_Tourist_ELECTION
- Mission_Sightseeing_Tourist_EXPANSION
- Mission_Smuggle
- Mission_Smuggle_Anarchy
- Mission_Smuggle_BLOPS
- Mission_Smuggle_BLOPS_CivilWar
- Mission_Smuggle_BLOPS_Extraction
- Mission_Smuggle_BLOPS_Lockdown
- Mission_Smuggle_BLOPS_War
- Mission_Smuggle_Boom
- Mission_Smuggle_Lockdown
- Mission_Smuggle_Outbreak
- Mission_Smuggle_RankFed
- Mission_Welcome_Assassinate
- Mission_Welcome_Collect
- Mission_Welcome_Salvage
- Mission_Welcome_Sightseeing

**Comment by sporebat** [comment]
Lowercase prefix checks FTW.

[`https://eddb.io/archive/v5/commodities.json`](https://eddb.io/archive/v5/commodities.json) has the commodity name to ID mappings we need for their form, but their form is designed to resist direct use.

We can link directly to INARA but the "where to buy close to you" feature would depend on the commander having INARA set up in EDMC and being logged in in their browser.

**Comment by sporebat** [comment]
`Commodity` values in the mission dump for which a lower case alphabet only check in `commodities.json` fails:

* `ComercialSamples`
* `HazardousEnvironmentSuits`
* `USSCargoRareArtwork`
* `MarineSupplies`
* `WreckageComponents`
* `MethanolMonohydrateCrystals`
* `USSCargoBlackBox`
* `BasicNarcotics`

That can't be comprehensive. @aarronc could you `SELECT DISTINCT` the `Commodity` and `Commodity_Localised` values from `MissionAccepted` events, and also the distinct `Type` values from `MarketBuy` events?

**Comment by sporebat** [comment]
![image](https://user-images.githubusercontent.com/23209850/45512616-9c261200-b7e3-11e8-960f-00b1632d87ba.png)

This scenario hadn't occurred to me. Reckon I should suppress this mission type?

**Comment by sporebat** [comment]
![image](https://user-images.githubusercontent.com/23209850/45515025-5f114e00-b7ea-11e8-9616-a161ed479eb1.png)

> NoneX None

What. Data delivery mission.

**Comment by aarronc** [comment]
![untitled-3](https://user-images.githubusercontent.com/1708701/45514963-c6a1ac00-b79e-11e8-8455-52eb924943b6.jpg)
i get an nonex none when taking a dontation mission. 

I was thinking of maybe having 3 lists. a stock up, a deliver to with the DestinationSystem displayed (for courier ones and passenger ones) and a general one of those pesky mission types like donation who dont fit the other 2 catagories

**Comment by sporebat** [comment]
I think I'll just suppress those. Need to dig into the events, though.

**Comment by sporebat** [comment]
Oh yeah don't forget the dump of unique `Commodity` + `Commodity_Localised` combinations in a CSV gist.

**Comment by aarronc** [comment]
had to hand compile this 

https://gist.github.com/aarronc/93db8ee7f499edd52265e72e91466889

**Comment by PsymonsB** [comment]
> Could use mechanize ( https://github.com/python-mechanize/mechanize ) to fill the form on eddb.io and submit ? but would have to distribute mechanize with the plug in, will work out a function tonight.

Seems this may be possible from urllib will spend some time on this this after noon

**Comment by aarronc** [comment]
excellent find! would be cool to see where this could lead

**Comment by PsymonsB** [comment]
![screengrab](https://user-images.githubusercontent.com/35759525/45579917-79e3d100-b883-11e8-88af-3d174b97a4c3.png) the ringed missions have been handed in ? also all these missions are mission specific cargo so can't pick them up

**Comment by sporebat** [comment]
There's no automatic check-off feature yet, no, and we need to filter on the mission type.

**Comment by sporebat** [comment]
Bit of a mismatch in the data. I can't find the identifiers for:

* methanol monohydrate crystals
* wreckage components

... and I'm missing name keys for:

* most or all of the rares
* thargoid technology sample
* prototype tech
* occupied cryopod
* time capsule

... and lots more I figure would vanish from `ED-Normal-Names-vs-Journal-names.csv`  if we filtered on the mission types. Still working on it.

**Comment by sporebat** [comment]
The Inara and EDDB numbers don't line up, e.g. for Time Capsule ([335](https://eddb.io/commodity/335) / [1012](https://inara.cz/galaxy-commodity/10212/)). I don't believe a trucker has yet been sent on a mission yet to get one of those, judging by the [sheet](https://gist.github.com/aarronc/93db8ee7f499edd52265e72e91466889), but there are no guarantees.

**Comment by sporebat** [comment]
I'm not sure I can check these off as the pilot picks up cargo, if only because it's hard to know which mission they'll hand it in for. Instead, I think I'll:

* make it a table
* add columns for how much this mission needs, and how much is in cargo
* add an indicator of whether the pilot has enough for one, all, or none
* check the missions off as they're done (`MissionCompleted`) or disappear (`Missions`)
* reduce the outstanding total as they're updated (`CargoDepot`)

Meanwhile, I think we can only sanely redirect people to EDDB for the time being as they're the only site that publish the name-to-number map. Mid term, I'll start collecting market data so we know which Hutton stations sell what.

**Comment by sporebat** [comment]
Let's just say it's a little more complicated than it sounds at first.

```python
TEST_EVENTS = [{
    'event': 'Cargo',
    'Inventory': [{
        'Count': 4,
        'Name_Localised': 'Uranium'
        'Name': 'uranium',
    }],
}, {
    'event': 'MissionAccepted',
    'Commodity_Localised': 'Uranium',
    'Commodity': '$Uranium_Name',
    'Count': 25,
    'MissionID': 415110664,
    'Name': 'Mission_Collect',
}, {
    'event': 'MissionAccepted',
    'Commodity_Localised': 'Uranium',
    'Commodity': '$Uranium_Name',
    'Count': 23,
    'MissionID': 415110665,
    'Name': 'Mission_Collect',
}, {
    'event': 'MissionAccepted',
    'Commodity_Localised': 'Uranium',
    'Commodity': '$Uranium_Name',
    'Count': 22,
    'MissionID': 415110666,
    'Name': 'Mission_Collect',
}, {
    'event': 'MarketBuy'
    'Count': 27
    'Type': 'uranium',
}, {
    'event': 'CargoDepot',
    'Count': 25,
    'ItemsDelivered': 25,
    'MissionID': 415110664,
    'TotalItemsToDeliver': 25
    'CargoType_Localised': 'Uranium',
    'CargoType': 'Uranium',
    'UpdateType': 'Deliver',
}, {
    'event': 'MissionCompleted',
    'MissionID': 415110664,
}, {
    'event': 'MarketSell',
    'Count': 1
    'Type': 'uranium',
    'Type_Localised': 'Uranium',
}, {
    'event': 'EjectCargo',
    'Count': 1
    'Type': 'uranium',
    'Type_Localised': 'Uranium',
}, {
    'event': 'Died'
}, {
    'event': 'MissionFailed',
    'MissionID': 415110665,
}, {
    'event': 'Missions',
    'Active': [],
}]
```

**Comment by PsymonsB** [comment]
Do we even need to tell them the number of each commodity. couldn't we just say seems like you need to find, Explosives, Bio-waste and Uranium. also market data can change every tick very dependent on faction states.

**Comment by sporebat** [comment]
Oh, is that what does it? I'll play with the display. No point committing to stuff that won't fit.

**Comment by sporebat** [comment]
Closing as sufficient enough for release. If you've found a bug or have an idea for improvement, raise another issue and mention this one.
