### ISSUE TITLE
 Proposed changes to EDMC 'Update' functionality

### ISSUE THREAD

**Issue by Athanasius** [aarronc/hutton-helper#86]
Please read https://github.com/EDCD/EDMarketConnector/discussions/1474 and comment if you think it might affect your plugin's use of the CAPI data, i.e. do you users correctly expect pressing 'Update' on the main EDMC UI to trigger something your plugin does ?

**Comment by PsymonsB** [comment]
we don't rely on the capi info and only journal prompts, we haven't told any users the update button does anything as we know what it does, but it doesn't stop them believing it does as it appears below our plugin in some instances
