### ISSUE TITLE
Transparent Mode

### ISSUE THREAD

**Issue by PsymonsB** [aarronc/hutton-helper#87]
Helper doesn't currently work in transparent mode no info in logs as to why, need further investigation.

**Comment by theMote** [comment]
Hi PsymonsB, not sure if this is related but I updated to the most recent EDMC (5.3.0) today and it started failing to show a GUI with the previous full Hutton Helper plugin (3.0.1).  I tried removing the previous plugin and installing the new 3.0.2 version and still no GUI.  I did see an EDMC process running in Task Manager (Windows 10), but I had to End Task it.  

When I removed the Hutton Helper all together EDMC would start up okay and show the GUI.  I was using the transparent mode.  When I added in the HH 3.0.2 the GUI would fail to show and I'd have to kill the EDMC process.  I tried variations, including upgrading Python from 3.4.4 to 3.10, but no success.  EDMC would run w/o the HH, but when I added it the GUI failed to show.  I looked into the logs and it showed an error (unfortunately I didn't save it) but it was something along the lines that the collection wasn't iterable and referenced the widgets.py file line 84.

I saw your comment and tried removing the HH, starting EDMC and then changing to the dark mode.  All went well.  Added HH back in and restarted EDMC and it came up fine.  

Sorry for the wall of text, just hoping it might help you pin this down.  I'm rubbish at Python.
